"""
Bridge between a Unitree Go2 robot and a web frontend, using the official
Unitree WebRTC protocol (the same one the Unitree Go / Unitree Explore
mobile apps use) via the `unitree_webrtc_connect` library. No jailbreak or
firmware modification needed.

Connects to the robot, subscribes to LiDAR / lowstate / sportmodestate /
wireless-controller data, decodes the video track to JPEG frames, and
exposes everything over a small Flask HTTP API for the NERO_GO2 web
dashboard to consume.

Generated by a local qwen2.5-coder:14b model (NERO_GO2 delegation workflow,
ld. docs/13-lokalis-llm-delegalas.md), reviewed and fixed by hand.

2026-09-01: élő robottal tesztelve és javítva. Két hibás API-feltételezés
derült ki, mindkettő a könyvtár forrásából (unitree_webrtc_connect
csomag, telepített verzió) ellenőrizve és javítva:
1. `conn.video` NEM async-iterálható — a `WebRTCVideoChannel` egy
   callback-regisztrációs API (`add_track_callback`), a driver saját maga
   hívja meg a track_handler-t, amikor megjön a videó track.
2. `conn.data_channel_pubsub` NEM létezik — a helyes útvonal
   `conn.datachannel.pub_sub`, és a `subscribe(topic, callback)` SZINKRON
   hívás (nem async generátor), sima (nem async) callback-kel.
Az RTC_TOPIC kulcsnevek is javítva lettek (`LOWSTATE` -> `LOW_STATE`,
`SPORTMODESTATE` -> `SPORT_MOD_STATE`) a csomag `constants.py`-ja alapján.
"""

import asyncio
import logging
import os
import threading
from typing import Optional

import cv2
import numpy as np
from flask import Flask, Response, jsonify

from unitree_webrtc_connect import (
    UnitreeWebRTCConnection,
    WebRTCConnectionMethod,
    RTC_TOPIC,
    AesKeyRequiredError,
    AesKeyRejectedError,
    RobotBusyError,
    LocalSignalingPortError,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("nero_go2.webrtc_bridge")

app = Flask(__name__)

# --- shared state, one lock guards all of it (simpler than per-key locks,
# and none of these updates are hot enough to need finer granularity) ---
_state_lock = threading.Lock()
_state = {
    "connected": False,
    "latest_jpeg": None,  # type: Optional[bytes]
    "lidar": None,
    "lidar_state": None,
    "lowstate": None,
    "sportmodestate": None,
    "wireless_controller": None,
}


def _set_state(**kwargs):
    with _state_lock:
        _state.update(kwargs)


def _get_state():
    with _state_lock:
        return dict(_state)


@app.route("/health")
def health():
    s = _get_state()
    return jsonify({"status": "ok", "connected": s["connected"]})


@app.route("/camera.jpg")
def camera_jpeg():
    s = _get_state()
    if s["latest_jpeg"] is None:
        return Response(status=404)
    return Response(s["latest_jpeg"], mimetype="image/jpeg")


@app.route("/lidar")
def lidar():
    s = _get_state()
    if s["lidar"] is None:
        return jsonify({"error": "no lidar data yet"}), 404
    raw = s["lidar"]

    # 2026-09-04, élő robottal tesztelve és dekódolva (/lidar_debug
    # segítségével, mert sem a könyvtár, sem a hivatalos példa nem
    # dokumentálja ezt pontosan): a raktári "libvoxel" dekóder
    # (unitree_webrtc_connect, ld. lidar/lidar_decoder_libvoxel.py) egy
    # voxel-mesh puffer-készletet ad vissza. A "positions" mező NEM
    # nyers float/world-koordináta, hanem fixpontos int16 rács-index,
    # 256-os (2^8) skálázással: valós_rács_index = raw_int16 / 256.0,
    # világkoordináta = origin + valós_rács_index * resolution. Ez
    # a datachannel-üzenet KÜLSŐ "data" mezőjéből (origin/resolution/
    # width) és a BELSŐ "data" mezőből (a decoder kimenete: positions/
    # uvs/indices/point_count/face_count) áll össze.
    try:
        outer = raw if isinstance(raw, dict) else {}
        inner = outer.get("data", raw) if isinstance(raw, dict) else raw
        positions = inner.get("positions") if isinstance(inner, dict) else None
        origin = outer.get("origin")
        resolution = outer.get("resolution")
        if positions is None or origin is None or resolution is None:
            return jsonify({"error": "no lidar data yet"}), 404
        arr = np.asarray(positions)
        grid_idx = arr.view(np.int16).astype(np.float32).reshape(-1, 3) / 256.0
        points = np.asarray(origin, dtype=np.float32) + grid_idx * float(resolution)
    except Exception:
        logger.exception("lidar decode failed")
        return jsonify({"error": "lidar decode failed"}), 500

    if len(points) > 5000:
        step = len(points) // 5000
        points = points[::step][:5000]
    return jsonify(points.tolist())


@app.route("/lidar_state")
def lidar_state():
    s = _get_state()
    if s["lidar_state"] is None:
        return jsonify({"error": "no lidar_state data yet"}), 404
    return jsonify(s["lidar_state"])


@app.route("/state")
def state():
    s = _get_state()
    return jsonify(
        {
            "lowstate": s["lowstate"],
            "sportmodestate": s["sportmodestate"],
            "wireless_controller": s["wireless_controller"],
        }
    )


def _subscribe(conn, topic, state_key):
    """Subscribe to one data-channel topic; the callback fires (synchronously,
    from the aiortc event loop) whenever a message for that topic arrives.
    `pub_sub.subscribe()` itself is a plain synchronous call, not async."""

    def _on_message(message):
        _set_state(**{state_key: message.get("data", message)})

    conn.datachannel.pub_sub.subscribe(topic, _on_message)


async def _video_callback(track):
    """Registered via conn.video.add_track_callback(). The driver already
    consumes+discards the very first frame before calling this, and awaits
    us directly from its pc.on("track") handler, so this just loops for
    the life of the track."""
    while True:
        frame = await track.recv()
        img = frame.to_ndarray(format="bgr24")
        ok, jpeg = cv2.imencode(".jpg", img)
        if ok:
            _set_state(latest_jpeg=jpeg.tobytes())


async def run_bridge():
    ip = os.environ.get("UNITREE_ROBOT_IP", "192.168.123.18")
    aes_key = os.environ.get("UNITREE_AES_128_KEY") or None

    conn_kwargs = {"ip": ip}
    if aes_key:
        conn_kwargs["aes_128_key"] = aes_key

    conn = UnitreeWebRTCConnection(WebRTCConnectionMethod.LocalSTA, **conn_kwargs)

    try:
        await conn.connect()
    except AesKeyRequiredError:
        logger.error(
            "Robot firmware requires a per-device AES-128 key (firmware >= 1.1.15). "
            "Fetch it with `unitree-fetch-aes-key` and set UNITREE_AES_128_KEY."
        )
        return
    except AesKeyRejectedError:
        logger.error("UNITREE_AES_128_KEY was rejected by the robot (wrong key).")
        return
    except RobotBusyError:
        logger.error(
            "Robot refused the connection - another WebRTC client (e.g. the "
            "official app) is already connected. Only one client at a time."
        )
        return
    except LocalSignalingPortError:
        logger.error("Neither port 9991 nor 8081 reachable on %s - check the IP/network.", ip)
        return

    _set_state(connected=True)
    logger.info("connected to Go2 at %s", ip)

    # A robot nem kezdi el ténylegesen küldeni a videó RTP-adatfolyamot,
    # amíg ezt a datachannel-üzenetet nem kapja meg (a "Track received"
    # log csak a transceiver negociálását jelzi, nem a tényleges adatot) —
    # ld. a könyvtár hivatalos példája: examples/go2/video/camera_stream/.
    conn.video.switchVideoChannel(True)
    conn.video.add_track_callback(_video_callback)

    # A LiDAR is csak explicit bekapcsolás után kezd adatot küldeni,
    # ld. a könyvtár hivatalos példája: examples/go2/data_channel/lidar/.
    # A robot alapból "traffic saving" módban visszatartja a bináris
    # LiDAR-adatot sávszélesség-spórolás miatt — ezt is ki kell kapcsolni
    # (ld. webrtc_datachannel.py "#Should turn it on when subscribed to
    # ulidar topic" megjegyzése a disableTrafficSaving metódus felett).
    await conn.datachannel.disableTrafficSaving(True)
    conn.datachannel.pub_sub.publish_without_callback(RTC_TOPIC.get("ULIDAR_SWITCH"), "on")
    _subscribe(conn, RTC_TOPIC.get("ULIDAR_ARRAY"), "lidar")
    _subscribe(conn, RTC_TOPIC.get("ULIDAR_STATE"), "lidar_state")
    _subscribe(conn, RTC_TOPIC.get("LOW_STATE"), "lowstate")
    _subscribe(conn, RTC_TOPIC.get("SPORT_MOD_STATE"), "sportmodestate")
    _subscribe(conn, RTC_TOPIC.get("WIRELESS_CONTROLLER"), "wireless_controller")

    try:
        # Subscriptions + the video callback all run as event-loop callbacks
        # from here on; just keep the loop alive until the connection drops.
        while conn.isConnected:
            await asyncio.sleep(1)
    finally:
        _set_state(connected=False)


def main():
    flask_thread = threading.Thread(
        target=lambda: app.run(host="0.0.0.0", port=5001, threaded=True, use_reloader=False),
        daemon=True,
    )
    flask_thread.start()
    asyncio.run(run_bridge())


if __name__ == "__main__":
    main()
