"""
Bridge between a Unitree Go2 robot and a web frontend, using the official
Unitree WebRTC protocol (the same one the Unitree Go / Unitree Explore
mobile apps use) via the `unitree_webrtc_connect` library. No jailbreak or
firmware modification needed.

Connects to the robot, subscribes to LiDAR / lowstate / sportmodestate /
wireless-controller data, decodes the video track to JPEG frames, and
exposes everything over a small Flask HTTP API for the NERO_GO2 web
dashboard to consume.

Generated by a local qwen2.5-coder:14b model (NERO_GO2 delegation workflow,
ld. docs/13-lokalis-llm-delegalas.md), reviewed and fixed by hand.

2026-09-01: élő robottal tesztelve és javítva. Két hibás API-feltételezés
derült ki, mindkettő a könyvtár forrásából (unitree_webrtc_connect
csomag, telepített verzió) ellenőrizve és javítva:
1. `conn.video` NEM async-iterálható — a `WebRTCVideoChannel` egy
   callback-regisztrációs API (`add_track_callback`), a driver saját maga
   hívja meg a track_handler-t, amikor megjön a videó track.
2. `conn.data_channel_pubsub` NEM létezik — a helyes útvonal
   `conn.datachannel.pub_sub`, és a `subscribe(topic, callback)` SZINKRON
   hívás (nem async generátor), sima (nem async) callback-kel.
Az RTC_TOPIC kulcsnevek is javítva lettek (`LOWSTATE` -> `LOW_STATE`,
`SPORTMODESTATE` -> `SPORT_MOD_STATE`) a csomag `constants.py`-ja alapján.
"""

import asyncio
import json
import logging
import os
import threading
from typing import Optional

import cv2
import numpy as np
from flask import Flask, Response, jsonify, request

from unitree_webrtc_connect import (
    UnitreeWebRTCConnection,
    WebRTCConnectionMethod,
    RTC_TOPIC,
    AesKeyRequiredError,
    AesKeyRejectedError,
    RobotBusyError,
    LocalSignalingPortError,
)
from unitree_webrtc_connect.webrtc_audiohub import WebRTCAudioHub, AUDIO_API


logging.basicConfig(level=logging.WARNING, format="%(asctime)s %(levelname)s %(message)s")
logging.getLogger("unitree_webrtc_connect").setLevel(logging.WARNING)
logging.getLogger("aiortc").setLevel(logging.WARNING)
logging.getLogger("aioice").setLevel(logging.WARNING)
logger = logging.getLogger("nero_go2.webrtc_bridge")

app = Flask(__name__)


@app.after_request
def add_cors_headers(response):
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Headers"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
    return response

# --- shared state, one lock guards all of it (simpler than per-key locks,
# and none of these updates are hot enough to need finer granularity) ---
_state_lock = threading.Lock()
_state = {
    "connected": False,
    "latest_jpeg": None,  # type: Optional[bytes]
    "lidar": None,
    "lidar_state": None,
    "lowstate": None,
    "sportmodestate": None,
    "wireless_controller": None,
}


def _set_state(**kwargs):
    with _state_lock:
        _state.update(kwargs)


def _get_state():
    with _state_lock:
        return dict(_state)


@app.route("/health")
def health():
    s = _get_state()
    return jsonify({"status": "ok", "connected": s["connected"]})


@app.route("/camera.jpg")
def camera_jpeg():
    s = _get_state()
    if s["latest_jpeg"] is None:
        return Response(status=404)
    return Response(s["latest_jpeg"], mimetype="image/jpeg")


@app.route("/lidar")
def lidar():
    s = _get_state()
    if s["lidar"] is None:
        return jsonify({"error": "no lidar data yet"}), 404
    raw = s["lidar"]

    # 2026-09-04, élő robottal tesztelve és dekódolva (/lidar_debug
    # segítségével, mert sem a könyvtár, sem a hivatalos példa nem
    # dokumentálja ezt pontosan): a raktári "libvoxel" dekóder
    # (unitree_webrtc_connect, ld. lidar/lidar_decoder_libvoxel.py) egy
    # voxel-mesh puffer-készletet ad vissza. A "positions" mező NEM
    # nyers float/world-koordináta, hanem fixpontos int16 rács-index,
    # 256-os (2^8) skálázással: valós_rács_index = raw_int16 / 256.0,
    # világkoordináta = origin + valós_rács_index * resolution. Ez
    # a datachannel-üzenet KÜLSŐ "data" mezőjéből (origin/resolution/
    # width) és a BELSŐ "data" mezőből (a decoder kimenete: positions/
    # uvs/indices/point_count/face_count) áll össze.
    try:
        outer = raw if isinstance(raw, dict) else {}
        inner = outer.get("data", raw) if isinstance(raw, dict) else raw
        positions = inner.get("positions") if isinstance(inner, dict) else None
        origin = outer.get("origin")
        resolution = outer.get("resolution")
        if positions is None or origin is None or resolution is None:
            return jsonify({"error": "no lidar data yet"}), 404
        arr = np.asarray(positions)
        grid_idx = arr.view(np.int16).astype(np.float32).reshape(-1, 3) / 256.0
        points = np.asarray(origin, dtype=np.float32) + grid_idx * float(resolution)
    except Exception:
        logger.exception("lidar decode failed")
        return jsonify({"error": "lidar decode failed"}), 500

    if len(points) > 5000:
        step = len(points) // 5000
        points = points[::step][:5000]
    return jsonify(points.tolist())


@app.route("/lidar_state")
def lidar_state():
    s = _get_state()
    if s["lidar_state"] is None:
        return jsonify({"error": "no lidar_state data yet"}), 404
    return jsonify(s["lidar_state"])


@app.route("/state")
def state():
    s = _get_state()
    return jsonify(
        {
            "lowstate": s["lowstate"],
            "sportmodestate": s["sportmodestate"],
            "wireless_controller": s["wireless_controller"],
        }
    )


_audio_hub = None
_loop = None

_BUILTIN_AUDIO_MAP = {
    "obstacle_avoidance": 3001,
    "obstacle_avoidance_exit": 3002,
    "companion_mode": 3003,
    "companion_mode_exit": 3004,
    "proximity_warning": 3001,
    "proximity_alert": 3001,
    "task_complete": 3003,
    "test": 3001,
}


@app.route("/audio/play/<sound_id>", methods=["POST", "GET", "OPTIONS"])
def play_audio(sound_id):
    if request.method == "OPTIONS":
        return jsonify({"status": "ok"}), 200
    if _audio_hub is None or _loop is None:
        return jsonify({"error": "audio hub not ready"}), 503
    try:
        api_id = _BUILTIN_AUDIO_MAP.get(str(sound_id).lower())
        if api_id is None and str(sound_id).isdigit():
            api_id = int(sound_id)
        if api_id is None:
            # Fallback to obstacle avoidance sound (3001) for any unmapped sound name
            api_id = 3001

        fut = asyncio.run_coroutine_threadsafe(
            _audio_hub.data_channel.pub_sub.publish_request_new(
                "rt/api/audiohub/request",
                {"api_id": api_id, "parameter": "{}"}
            ),
            _loop
        )
        res = fut.result(timeout=5)
        return jsonify({"status": "ok", "played": sound_id, "api_id": api_id, "result": res})
    except Exception as exc:
        logger.exception("audio play error")
        return jsonify({"error": str(exc)}), 500


@app.route("/audio/megaphone", methods=["POST", "OPTIONS"])
def play_megaphone():
    if request.method == "OPTIONS":
        return jsonify({"status": "ok"}), 200
    if _audio_hub is None or _loop is None:
        return jsonify({"error": "audio hub not ready"}), 503

    if "file" not in request.files:
        return jsonify({"error": "no file uploaded, expected multipart 'file'"}), 400

    file = request.files["file"]
    tmp_path = "/tmp/uploaded_speech.wav"
    file.save(tmp_path)

    async def _stream_megaphone():
        await _audio_hub.enter_megaphone()
        await asyncio.sleep(0.3)
        res = await _audio_hub.upload_megaphone(tmp_path)
        await asyncio.sleep(0.5)
        await _audio_hub.exit_megaphone()
        return res

    try:
        fut = asyncio.run_coroutine_threadsafe(_stream_megaphone(), _loop)
        res = fut.result(timeout=30)
        return jsonify({"status": "ok", "result": res})
    except Exception as exc:
        logger.exception("megaphone error")
        return jsonify({"error": str(exc)}), 500


@app.route("/api/speak", methods=["POST", "OPTIONS"])
@app.route("/audio/speak", methods=["POST", "OPTIONS"])
def speak_text():
    if request.method == "OPTIONS":
        return jsonify({"status": "ok"}), 200
    data = request.json or {}
    text = data.get("text", "")
    if not text:
        return jsonify({"error": "text required"}), 400

    tmp_path = "/tmp/tts_speech.mp3"
    try:
        from gtts import gTTS
        tts = gTTS(text=text, lang="hu")
        tts.save(tmp_path)
    except Exception:
        os.system(f'espeak-ng -w /tmp/tts_speech.wav "{text}" || echo "TTS"')
        tmp_path = "/tmp/tts_speech.wav"

    async def _stream_tts():
        if _audio_hub:
            await _audio_hub.enter_megaphone()
            await asyncio.sleep(0.3)
            res = await _audio_hub.upload_megaphone(tmp_path)
            await asyncio.sleep(0.5)
            await _audio_hub.exit_megaphone()
            return res
        return "audio hub unavailable"

    try:
        if _audio_hub and _loop:
            fut = asyncio.run_coroutine_threadsafe(_stream_tts(), _loop)
            res = fut.result(timeout=30)
            return jsonify({"status": "ok", "text": text, "result": res})
        else:
            return jsonify({"status": "ok", "text": text, "simulated": True})
    except Exception as exc:
        logger.exception("tts speak error")
        return jsonify({"error": str(exc)}), 500




def _subscribe(conn, topic, state_key):
    """Subscribe to one data-channel topic; the callback fires (synchronously,
    from the aiortc event loop) whenever a message for that topic arrives.
    `pub_sub.subscribe()` itself is a plain synchronous call, not async."""

    def _on_message(message):
        _set_state(**{state_key: message.get("data", message)})

    conn.datachannel.pub_sub.subscribe(topic, _on_message)


async def _video_callback(track):
    """Registered via conn.video.add_track_callback(). The driver already
    consumes+discards the very first frame before calling this, and awaits
    us directly from its pc.on("track") handler, so this just loops for
    the life of the track."""
    while True:
        frame = await track.recv()
        img = frame.to_ndarray(format="bgr24")
        ok, jpeg = cv2.imencode(".jpg", img)
        if ok:
            _set_state(latest_jpeg=jpeg.tobytes())


async def run_bridge():
    global _audio_hub, _loop
    _loop = asyncio.get_running_loop()

    while True:
        ip = os.environ.get("UNITREE_ROBOT_IP", "192.168.123.161")
        aes_key = os.environ.get("UNITREE_AES_128_KEY") or None

        conn_kwargs = {"ip": ip}
        if aes_key:
            conn_kwargs["aes_128_key"] = aes_key

        conn = UnitreeWebRTCConnection(WebRTCConnectionMethod.LocalSTA, **conn_kwargs)

        try:
            await conn.connect()
        except Exception as e:
            logger.warning("WebRTC connect attempt error (%s), retrying in 5s...", e)
            await asyncio.sleep(5)
            continue

        _set_state(connected=True)
        logger.info("connected to Go2 at %s", ip)

        try:
            _audio_hub = WebRTCAudioHub(conn)
            logger.info("WebRTCAudioHub initialized")
        except Exception as exc:
            logger.warning("WebRTCAudioHub init warning: %s", exc)

        try:
            conn.video.switchVideoChannel(True)
            conn.video.add_track_callback(_video_callback)
        except Exception as e:
            logger.warning("Video channel setup warning: %s", e)

        try:
            await conn.datachannel.disableTrafficSaving(True)
            conn.datachannel.pub_sub.publish_without_callback(RTC_TOPIC.get("ULIDAR_SWITCH"), "on")
            _subscribe(conn, RTC_TOPIC.get("ULIDAR_ARRAY"), "lidar")
            _subscribe(conn, RTC_TOPIC.get("ULIDAR_STATE"), "lidar_state")
            _subscribe(conn, RTC_TOPIC.get("LOW_STATE"), "lowstate")
            _subscribe(conn, RTC_TOPIC.get("SPORT_MOD_STATE"), "sportmodestate")
            _subscribe(conn, RTC_TOPIC.get("WIRELESS_CONTROLLER"), "wireless_controller")
        except Exception as e:
            logger.warning("Datachannel subscriptions warning: %s", e)

        try:
            while conn.isConnected:
                await asyncio.sleep(1)
        finally:
            _set_state(connected=False)
            logger.info("WebRTC disconnected, reconnecting in 3s...")
            await asyncio.sleep(3)


def main():
    flask_thread = threading.Thread(
        target=lambda: app.run(host="0.0.0.0", port=5001, threaded=True, use_reloader=False),
        daemon=True,
    )
    flask_thread.start()
    
    while True:
        try:
            asyncio.run(run_bridge())
        except Exception as e:
            logger.error("run_bridge exception: %s, restarting in 5s...", e)
            import time
            time.sleep(5)


if __name__ == "__main__":
    main()
